### ISSUE TITLE
Allow DRCJs to craft additional custom content in email notifications to competitors

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#249]
Provide an interface in Session Manager (or perhaps Convention Manager), that allows the DRCJ to define and append additional custom information to the automatic emails that are sent to competitors. For example, when he APPROVES their entry, their approval email could also contain convention registration info, directions to venue, URL to a website, etc.

**Comment by dbinetti** [comment]
Would this be at the Session level or Convention level?

Stuff that is convention level is more easily added by the SJCJ. Stuff at the Session level more easily added by the DRCJ.  (Session level also means it would be added potential twice, depending on chorus/quartet focus)

**Comment by millsjdm** [comment]
This would more likely be at the Session level - especially considering
that the DRCJ should be doing this work. (I certainly don't want to have to
"gather up" 17+ different sets of "custom email" content scripts, and then
go into each Convention and into each session to "attach" that data).

I see the DRCJ doing it before he "opens" the session (to potentially
augment those "hey, the session is now open for competitor entry" emails) -
as well as later on, before he "closes" the session (to potentially augment
those "hey, we're all set to go and here is the draw" emails).

Yes - it would likely be potentially 2 different "focuses" (quartets vs
choruses) - so the DRCJ might choose to have slightly different verbiage
for those two groups.

This is *definitely *a LOW priority feature enhancement to be considered
for next Spring.

*J. David Mills*
BHS C&J Committee Chairman
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*

**Comment by millsjdm** [comment]
the added comment field (in Convention Manager) is okay... but doesn't fully address this feature request. The information that the DRCJ might like to send is not just "static" text attached ahead of time at the "convention" level - (and then attached to EVERY email sent throughout the Session life-cycle). Instead, it would be current information he might wish to add dynamically to a SPECIFIC set of auto-generated emails just prior to pressing the "Close Session" and/or "Verify Session" buttons in Session Manager (such as quartet grid info or chorus director meeting time, etc.).

**Comment by dbinetti** [comment]
I'm closing this issue.  The functionality is there if and when you want to turn it on.

**Comment by millsjdm** [comment]
Thanks - I'll keep this bookmarked... we will plan to roll this new
implementation out prior to the Fall contest season. I'll use one DRCJ to
serve as a tester.

*J. David Mills*
SCJC Chairman 2016-2019
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*
