### ISSUE TITLE
Add Custom Features for Competitors to Choose Their Eval Option

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#251]
When a competitor enters a contest, the legacy Contest Manager allowed the competitor to choose one of three eval options: 1. No Eval 2. Eval Only 3. Coaching Eval
We could do this of course again, but what DRCJs really want is a way to build their own "menu" options for competitors to choose each time they "setup a contest" in Session Manager. Some would perhaps not provide any options, so it would be blank. Others would maybe use these "old" 3 options. Others would like to have the ability to create their own unique list of options.

**Comment by dbinetti** [comment]
I'm not understanding.  Are there different types of evals offered?  or are you saying sometimes no evals are possible at all and that needs to be done at the convention manager level?

**Comment by millsjdm** [comment]
Two things:

1) Some competitors know in advance that they won't be able to be around at
all for any eval. Some competitors know in advance that they won't be able
to benefit from evaluation  coaching sessions (out "normal" offering) - and
so they opt to just have perhaps a quick 10-minute "A&R". Some competitors
just don't want an eval at all. If DRCJ knows these things in advance, he
can create (along with the CA) an evaluation matrix that optimizes the
post-contest evaluation schedule more efficiently.

2) Some districts are now expanding competitor options to "choose your own
eval" preferences. Where (in DIX for example) - it is more of an "a la
carte" menu of options. Such as: ..."we just want PER for 60 mins., no SNG,
no MUS" - or "...we'd prefer 30 mins. each for MUS & SNG with no PER".

The legacy CJ-20 Contest Manager provided a place for their preferences
regarding a static choice (item #1). So at the very least, we'll want to
get that built into the competitor entry piece in Barberscore for the
Spring. Ideally, we'd like to also support those districts (like DIX) - who
wish to build their own menu of options each time just before they open the
session. The reason they would need it "each time" is that each venue &
each season will present different challenges as to what menu options would
be practical to offer competitors.

Again - this is not a "CRITICAL" requirement by any means. In the old days
before CM (as well as this Fall) - DRCJs are handling this offline via
email/phone, etc.

--David

*J. David Mills*
BHS C&J Committee Chairman
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*

**Comment by dbinetti** [comment]
well, the reason I was asking is because #1 is already in there.  "Include
Eval/No Eval" button in preferences.

I can add a free-form field for whatever needs to be conveyed

**Comment by millsjdm** [comment]
Well almost already there. The "legacy" options were:
1. No Eval
2. Non-coaching Eval (which normally meant only 10 mins of feedback per category)
3. Eval (which normally meant 20 mins of feedback/coaching per category)

**Comment by dbinetti** [comment]
FWIW, we decided -- I think this may have been Randy or Chris -- to
simplify to a boolean.  Does it really matter beyond that?

If you want this, no problem.  But it will require me to recast the
variable,.

**Comment by millsjdm** [comment]
Keep it as is for now.
The "build your own menu" option is definitely an advanced "future feature"
request.

*J. David Mills*
BHS C&J Committee Chairman
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*

**Comment by millsjdm** [comment]
the - yes/no option is good for now. We will consider a customized menu option later as an advanced feature
