### ISSUE TITLE
Duplicate Session Listings appearing on Session Manager Page

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#252]
Some sessions only appear once, others show duplicates. See attached screen shot.
LOW PRIORITY.
![extra duplicate listings](https://user-images.githubusercontent.com/30165860/28997426-7069a964-79e2-11e7-9746-0b812f990f42.jpg)

**Comment by millsjdm** [comment]
this now appears to be fixed.... ???

**Comment by dbinetti** [comment]
ok, close
