### ISSUE TITLE
Let's discuss strategy for removing Repertory "mistakes"

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#254]
VERY LOW PRIORITY

Currently, when a competitor (or DRCJ) adds a song to the competitor repertory - once added, it can't be "deleted" - one can only change to an "inactive" state. Which is good, because we don't want to "orphan" that song association in our system if they've actually used that song in a contest.
However, we will continue to see more and more "mistakes":
1. Competitor chooses/adds/saves the wrong chart, then goes back in to try to "fix" it.
2. Competitor is "messing around" with the Repertory feature, and is adding one or two "test" charts just to see how the system works.
In either case - that chart will be in their repertory (listed as "Inactive") forever.

We should figure out the best approach for removing the eventual "clutter". (Currently, I just delete the chart from their repertory on the back-end when an experimental "test" chart was added and now should be deleted).

We can just continue to take that approach... (perhaps having them send an email to a Barberscore admin). Where we could then verify that the chart can indeed be safely deleted. I'm open to other ideas.

**Comment by dbinetti** [comment]
This has been addressed; competitors can remove their repertory entries.
