### ISSUE TITLE
*URGENT PRIORITY* - SWD Convention only lists District-level Awards

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#255]
For this Fall, the only Convention that includes both District-level as well as Division-level awards is the SWD Convention. To be fixed: All SWD Division awards need to be included as an available award for this upcoming convention.

Longer term: In the Spring, several more District conventions will be needing to include one or more division awards for their contest sessions. We either need to include ALL awards (District-level as well as "sub-organization" Division-level awards) for ALL conventions within a District handled by that DRCJ - or -
we need to include in the SCJC "setup" for the convention ahead of time that identifies which "sub-organizations" will be involved in that particular convention - so only those awards are available to the DRCJ.

**Comment by dbinetti** [comment]
I've picked this up during testing.  the short answer is that you'll add a
new set of fields -- "grantors" -- which will effectively delineate what
awards are available.  haven't built the interface for it yet.

**Comment by dbinetti** [comment]
as a workaround I can add them manually after Randy has done his stuff

**Comment by millsjdm** [comment]
So... should I have Randy "open" the contest (selecting only those
available district-level awards)? Then you'll add them?

However (if yes): How might that impact any competitors that attempt to
enter the contest prior to those updates?

*J. David Mills*
BHS C&J Committee Chairman
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*

**Comment by dbinetti** [comment]
yes, this would be the case.  let me do testing on staging to see if we can
take another approach.

**Comment by millsjdm** [comment]
Ok

David Mills - (813) 786-4381
[sent from my Galaxy Note5]

**Comment by dbinetti** [comment]
this is now fixed.

**Comment by millsjdm** [comment]
looks good

**Comment by millsjdm** [comment]
Looks good for the Chorus Session. We still need the SWD division awards
for the Quartet Session.

Thanks!

*J. David Mills*
BHS C&J Committee Chairman
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*

**Comment by dbinetti** [comment]
done
