### ISSUE TITLE
*HIGH PRIORITY* All potential competitors (to later be invited) receiving email when contest session is open.

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#258]
[EVG use case] In addition, will there be another email sent to the competitor if DRCJ clicks "Delete Entry"? (Just checking). Bottom line, they should not receive one, if they were never invited.
Note: I will hold off on having any other DRCJs (with "Invited" sessions) open their contests just yet, until we can address this. Let me know. Thanks!

**Comment by dbinetti** [comment]
ok, I think I fixed this
