### ISSUE TITLE
Let's consider making all 4 quartet members an Admin by default

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#261]
This would solve many issues we're starting to experience... and I really can't think of any reason why we wouldn't want this to be the default in Barberscore. I understand the logic for a single "contact person" (for paying quartet subscriptions) in the Member Center - but we normally want to communicate with all 4 members anyway.
All 4 would get an "open session" or "invite" email. All 4 would get the verification/draw email. All 4 would be able to add to repertory and handle contest entry.
If one or more of them wishes to stop getting any of those "admin role" emails - they can just toggle the "not-admin" switch.

**Comment by dbinetti** [comment]
so the only reason not to do this currently is that I don't know who is
active and inactive.  there are some quartets with a dozen members, all
active.

remember, the BHS cares about active in terms of paid membership; we care
about active for a different reason.  if we make everyone an admin then
former members (who might not have left on good terms) would be able to
wreak havoc, including locking out current members.

**Comment by millsjdm** [comment]
Good point... I'd forgotten about all of those use cases...  darn.

David Mills - (813) 786-4381
[sent from my Galaxy Note5]
