### ISSUE TITLE
Change Award Toggles To "On" for DRCJs

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#264]
When a DRCJ gets ready to open a new contest session, the default setting for each of the available awards should be "on"
Two reasons:
1. Most always, all awards will need to be turned on prior to opening the contest session
2. Opening a session with a missing award requires an Admin to "fix"

**Comment by dbinetti** [comment]
Yeah, this actually needs a better architecture that avoids the second reason.  But default on works regardless.
