### ISSUE TITLE
Change "active" Chorus Participants Toggle Default to "On"

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#265]
If possible - identify all active chapter members - using our internal definition of "active" (less than 6 months expired) - and set these by default to "on" for participating on stage, leaving the others as "off".
Rationale: It then becomes easier for the chorus Admin to "turn off" those men that are NOT going to compete - as opposed to explicitly setting the toggle to "on" for the majority of members.

**Comment by dbinetti** [comment]
The issue is going to be with chapters that have extensive "remote" members.

Instead, I propose that we simply default to ON all those who participated in the most recent contest.  It's not perfect, but it will get most choruses to where they need to be.

**Comment by millsjdm** [comment]
That'll work - great idea. Easier to add & subtract from contest to contest
rather than starting from scratch each time.

David Mills - (813) 786-4381
[sent from my Galaxy Note5]
