### ISSUE TITLE
Hide "Verify Session" button except...

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#269]
To draw attention to the current state of the "official" draw prior to a DRCJ verifying the session - hide the "Verify Session" button on all tabs - EXCEPT on the [Draw] tab.

**Comment by dbinetti** [comment]
This would actually introduce a complexity that I'm not willing to accept.  So let's find a different solution to the problem (if necessary; I haven't seen this be an issue for anyone.)
