### ISSUE TITLE
Automatically create new `User` when a `Person` becomes an Admin

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#271]
Currently, when an Admin of a group designates another member of that group to be an additional Admin - they still are unable login to Barberscore unless they were already an Admin of another group.
If possible, recommend (that when someone is granted Admin status) an algorithm does a check of the Users table to see if that Person's email is already included - if not, add a new User to associate with the Person.

**Comment by dbinetti** [comment]
All persons are now users, so this is no longer relevant.
