### ISSUE TITLE
Prevent Inactive Quartets from Entering a Contest

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#272]
The UI should not allow an Admin for an inactive quartet to enter that quartet into a contest. I fairly certain that our inactive flag (connected to a quartet) is propagated from the Member Center - and that the Member Center handles the status of that flag based on the expiration of that quartet subscription. (At least it appears that way).

**Comment by dbinetti** [comment]
This is done.

**Comment by millsjdm** [comment]
awesome!
