### ISSUE TITLE
withdrawn v. scratch

### ISSUE THREAD

**Issue by dbinetti** [barberscore/barberscore-api#381]
Catching up on earlier thread — “Delete appearance” worked to remove competitor from round.  The issue became how to show the ‘deleted’ group’s scores from round 1. The QS OSS is already generated and round finished.  However, its QS scores are not shown on the QF OS - as they are in legacy with a ‘withdrawn’ footnote automatically generated. How do we provide this?

**Comment by dbinetti** [comment]
This is now in place, modulo this question @millsjdm or @CLBuechler:  what else need we do for scratches, aside from removing them from the OSS, SA and any other references?  Do they need show up in a footnote?  something else?

Referred in 69b6f93a

**Comment by CLBuechler** [comment]
If it withdraws from a second round finals (QF), we need footnote that it withdrew and its QS scores need to appear on Finals OSS and SA.  If it withdraws from QS or CF, no footnote necessary.

**Comment by dbinetti** [comment]
So I'm now looking at this ticket and have some questions.

I've never seen this presented in a legacy OSS -- meaning, I've never seen prior-round scores presented from a withdrawn competitor.  I don't quite know how to render it.  It doesn't really fit in the actual presentation of scores, and so would I create a whole other table?   Can you show me an example?

As an aside, this is actually going to be a very difficult thing to do.  Again, I'll do it if it's necessary, but I'm just wondering if that's the case.  

Obviously scores are preserved, and CSAs are generated.  Those are easy.  Just not sure how to get this on the OSS in a way that makes sense.

**Comment by millsjdm** [comment]
Hmm... I'm not aware of a real example - (but perhaps Chris can show one).
My thought would be perhaps a "revised" OSS that could be created
(manually) later after the fact?

In either case, this is definitely a LOW priority prior to Intl. - beyond
(for the Fall) - I'll let Chris speak to that.

*J. David Mills*
SCJC Chairman 2016-2019
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*

**Comment by dbinetti** [comment]
I'm done with things for International.  So again, if there are issues
there please raise and label them since those get priority interrupt.  But
as of now I believe International is fully ready.  I'm working on the punch
list now because I'd like to get that stuff done asap so I can move on.

**Comment by CLBuechler** [comment]
EZPZ  Yes, it does occur. Two samples attached.

Since new OSS is not ranked at districts, couldn’t the withdrawn group simple be listed at end with two songs? Admittedly the might not be simple...

**Comment by CLBuechler** [comment]
Thank you, Dave.  I’m also done with international testing. Absent a server error I am confident of how things will work. I honestly cannot deal with more any exchanges right now.

I replied to your request with examples.

— Chris

**Comment by dbinetti** [comment]
No attachments.

The reason it isn't easy is because I'm pulling information from a prior
round.  Not impossible, just difficult.

Yep, I get it.  I'm still going to ask questions just because I'm working
on stuff now; don't feel compelled to respond.  I just want to get things
out while I"m thinking about them.
