### ISSUE TITLE
no image

### ISSUE THREAD

**Issue by dbinetti** [barberscore/barberscore-api#390]
Instead of the default "no image available" image - could we replace with a link that reads something like: "No image available - click here to learn how to submit an image for your group"

**Comment by dbinetti** [comment]
We do this on the site already.  are you saying put a notice in the CSA itself?

**Comment by millsjdm** [comment]
Yes - basically a link that directs them to an FAQ (or something) that tells them how to do it.

**Comment by dbinetti** [comment]
Closing this pending the MC fixing this issue
