### ISSUE TITLE
Award presentation

### ISSUE THREAD

**Issue by dbinetti** [barberscore/barberscore-api#393]
The Awards footnote area showed only one qualifer in the SUN Quartet Finals OSS.

**Comment by millsjdm** [comment]
Alpha is best for the OSS. However, since the announcements sheet will need it by score (from lowest to highest), if it is easier to make them both the same, that is fine.

**Comment by dbinetti** [comment]
Chris: how are qualifiers being determined?

db: Via the algorithm we discussed (mostly David I think) last year.  These algos are encapsulated in the relevant award.  So, checking out SUN International Quartet Qualifier, for instance, the auto-advance bar is 73.0 (advancing from Friday to Saturday), the auto-qual threshold is 76.0, and the minimum required is 70.0.

**Comment by CLBuechler2324** [comment]
Do we have qual thresholds for district (overall) qualifiers? I'm asking since NED changed it's level

**Comment by CLBuechler2324** [comment]
DUH!!! I update that myself in awards.  Sorry.  Didn't get much sleep last night.
