### ISSUE TITLE
announcements formatting

### ISSUE THREAD

**Issue by dbinetti** [barberscore/barberscore-api#398]
The announcements sheet needs attention. Please work with Chris for a resolution. However, regardless of how much can be automated/calculated correctly - the CA will still need to have the ability to manually add/remove/edit the final rendering of the announcements print out.

**Comment by dbinetti** [comment]
I'm officially assigning this ticket to @CLBuechler  so he can tell me what is needed.  I think I'm simply going to render this as a  Word doc, which will allow for complete flexibility.  however, I still need to know generally what's needed.

**Comment by dbinetti** [comment]
Still waiting on input from @CLBuechler for this ticket

**Comment by CLBuechler2324** [comment]
It's a discussion item for DRCJs and CAs in SLC and CatSchool. Do we really need an interactive option  or can we simply have programmatic and scratch out anything not desired? E.g., top 5 for every championship and list for qualifiers.

**Comment by dbinetti** [comment]
We don't need it to be interactive at all -- the easiest thing to do is make it a Word doc and then people edit it to their heart's content.  But I'm not advocating any particular approach -- I'm just responding to David's request to work with you to figure out whatever the solution is.

**Comment by dbinetti** [comment]
This is now presented as a Word doc.  I can edit the defaults as requested.  Attached is a mock. 
[BHS Spring 2019 International Convention Quartet Finals Announcements.docx](https://github.com/barberscore/barberscore-api/files/3304496/BHS.Spring.2019.International.Convention.Quartet.Finals.Announcements.docx)

**Comment by dbinetti** [comment]
I'm just going to deal with this by responding to ad hoc requests.  Functionality is in place

**Comment by CLBuechler2324** [comment]
Word works fine. Thx
1) Would reverse sort order from 1-5 to 5-1
2) Default should be all qualifiers for qualifier contest, top 5 for all championship contests and 1 for representative/improved/manual contests.  Much easier to delete in Word than have to type contests.
