### ISSUE TITLE
renumber outcomes

### ISSUE THREAD

**Issue by dbinetti** [barberscore/barberscore-api#454]

**Comment by dbinetti** [comment]
@CLBuechler @millsjdm would you please comment on the current numbering scheme for outcomes (ie, for awards at the bottom of the OSS).  is this the order that you want?

**Comment by millsjdm** [comment]
I don't have a preference on listing of awards... but perhaps Chris would like to use the same "priority" as he has been using in legacy for consistency purposes. I'll defer to his input.... Chris?

**Comment by dbinetti** [comment]
Closing in favor of #511
