### ISSUE TITLE
address MT/Eval-only in subsequent rounds

### ISSUE THREAD

**Issue by dbinetti** [barberscore/barberscore-api#462]

**Comment by dbinetti** [comment]
We need a way to indicate Eval only in subsequent rounds, slightly differently than MT

**Comment by dbinetti** [comment]
See comment thread re: button/no-button

**Comment by millsjdm** [comment]
Required end state: Any group that gets scored (to include the MT) in any round that is not competing for an award should be added to footnote - "The following groups performed for evaluation score only:".

**Comment by CLBuechler2324** [comment]
Only reason I see for MT distinction is to lock in draw position 0.  I don't have issue if Final MT is named on OSS as Score/Eval only.

**Comment by dbinetti** [comment]
given that the MT is programmatically applied in either case I don't
see the advantage of a button.  but I do need to program in the
footnotes

**Comment by dbinetti** [comment]
OK, I've put this in place such that all appearances with OA <=0 appear as "eval only".

Moving forward, I think the more explicit, consistent approach is to have a flag that specifically indicates "Eval Only", which defaults for True for all appearances added after the first round.  That way the CA can put the new appearance at any order in the draw they wish (provided it doesn't conflict with an earlier appearance).  Yes, its a tiny bit more cluttered, but overall I think would be better.  Thoughts?

**Comment by CLBuechler2324** [comment]
Sounds good.

Chris

**Comment by millsjdm** [comment]
That works!

**Comment by dbinetti** [comment]
Actually, we can probably make this even simpler:  is it a frequent occurrence that Groups are added to a subsequent round but also eligible for awards?  I wouldn't think so:  in fact, I'm not sure how it's possible since for subsequent rounds the adjudication is already half-done.  

If this is true, then we can skip the button altogether and simply assume "anyone added to subsequent rounds (either MT or otherwise) are Eval-Only by definition.  Right?  If this never happens or is truly rare, then perhaps we just handle on backend....

**Comment by millsjdm** [comment]
Your assumption is correct.
There are other use cases however when we know (in advance) that a district wishes to hold a 1-round contest on Saturday night (such as a Youth Quartet Award). For now, we've been handling these use cases by creating an additional contest session to accommodate that contest/award - since all of the other Saturday night groups will have already sung the previous round.

**Comment by dbinetti** [comment]
are these actual new sessions?  (are they grouped together, new panel,
separate draw, etc.) or should we be thinking about this use case?

**Comment by millsjdm** [comment]
It is so rare, we're not concerned. (It only happened once last Spring, I think). For this issue, I'd like to keep this implementation clean. If a new group is added to a Finals round, then they are "evaluation score only" - no new awards.

**Comment by dbinetti** [comment]
Fixed in 3c546ba9.
