### ISSUE TITLE
Add Gender to Group Member Info

### ISSUE THREAD

**Issue by CLBuechler2324** [barberscore/barberscore-api#484]
Had request to add Gender (in Person record) as viewable field in Group Members. Appears to enough space btwn current fields to permit this.

**Comment by dbinetti** [comment]
Closed in f828f75

**Comment by CLBuechler2324** [comment]
Seeing Gender label at top of column but not data.  When is it populated? I refreshed.

**Comment by dbinetti** [comment]
the usual -- needs time to deploy.

**Comment by CLBuechler2324** [comment]
I will be patient - 🤓

Thank you!

**Comment by dbinetti** [comment]
should be active now -- that's what I see

**Comment by CLBuechler2324** [comment]
Thanks.  I’ve moved on to other issue
