### ISSUE TITLE
Proper ranks in SA report

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#490]
When there is a tie for score rank on the SA (either total or for a category), the next rank number should be skipped - (such as in looking at a golf score leader board).  I located a Python class called Ranking. It looks like it would do the job for us.

Available here: https://pypi.org/project/ranking/

**Comment by dbinetti** [comment]
yes, this is the same library we were using before.  however, it requires a
different approach.

to use Ranking, you need to pull each set of ordered scores into memory,
one for each category and overall -- four total.  this is expensive.

without it (which is what we're doing now) it's a single database call and
done.

so the short answer is: yes, can be done, but not cheap so just let me know
if it's important

**Comment by millsjdm** [comment]
Definitely not important enough for expensive CPU cycles. We can adjust to the "new" ranks. :-)

**Comment by dbinetti** [comment]
There is a new class that can do this "golf" ranking easily.  Would you like it implemented @millsjdm? Copy @CLBuechler

**Comment by millsjdm** [comment]
Uh... yes! Thanks!

*J. David Mills*
SCJC Chairman 2016-2019
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*

**Comment by millsjdm** [comment]
we'll definitely need it for International OSS ranks

*J. David Mills*
SCJC Chairman 2016-2019
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*

**Comment by CLBuechler** [comment]
Thought: For international OSS ranking ties are broken.  With traditional ”golf” ranking only first-place tie results in playoff.

**Comment by dbinetti** [comment]
This issue is solely for the SA report.  For OSS please comment on #492 

So, @millsjdm, for the SA report only:  category ranks will have Golf Ranking.  What about overall ranking?  Is that golf also or do we use tie-breaker algo?
