### ISSUE TITLE
Steve Curulla Feedback on PSA

### ISSUE THREAD

**Issue by dbinetti** [barberscore/barberscore-api#493]
On the report layout:

·         The layout is very nice.  It’s clean and easy for the reader to get oriented.

·         Picking up our picture from the roster database is pretty cool.

·         It would be helpful to have a footer with the explanations of how to read the report (as were included in the email).  Human nature being what it is, it will be helpful to have those notes on the report itself.

·         For the Finals reports, I suggest listing the order of songs by quartet in the order the quartet performs them over the weekend, i.e. semi-finals first, then finals.  I think the goal of this report is to help identify trends, and using a chronological order would help.

·         The order of StdDev/Diff/Avg columns, would be more logical if the StdDev and Avg columns were next to each other, since I believe these two columns are the most related.  The Diff numbers are based on an average that is not shown. 

·         Following up on the comment above about the category average not being shown, I suggest you should think about the value of showing the overall panel average per song but not the category average.  The inconsistency causes confusion.  If the goal of this report is to show differences, then it seems that showing the panel average is unnecessary (we will have that on the SA).  I don’t really know what the purpose of this report is, but the inconsistency is confusing, and perhaps an opportunity to free up real estate. 

 

On the use of the report:

·         What’s the “call to action”?  What problem is this trying to fix? 

·         Is there an expected result or picture that we are supposed to be looking for or working towards?  Are we expecting to see MUS on the left, PER in the middle, and SNG on the right?

·         How do we use this in conjunction with the K-P report?  

·         The report is very colorful, and color draws our attention.  However, this report is heavily influenced by “tie-breaker” rules in the report when judges in different categories assign the same score to a performance.  In general, when you look at the overall report, the color pattern shows yellow skewed to the left and blue skewed to the right.  This is exaggerated because of how scores that are the same across the categories are treated: it appears that MUS is generally (but not always) reported first and SNG scores are generally reported last.  There were lots of performances in the JAD contests where 3 out of the 6 judges assigned the same numeric score, and even a few where 4 of the 6 judges had the same score.  If I was one of the 4, my score could be, for example, anywhere from column 2 to column 5 out of the 6.  I don’t think there were any performances where at least a couple judges had the same score.  That means that for pretty much every song, hard-coded reporting rules have a heavy hand in the final report.  This makes it harder to know what I should do with this report.

 

On the rollout:

·         It will be helpful if there is some sort of broadcast email from David Mills about the new PSA reports (and perhaps a general update on Barberscore).  Most of us have no idea of what’s going on with Barberscore, or the scope of the project at this point.  As it happened this weekend, the new PSA showed up in my inbox about the same time as the SA.  Since I did not remember hearing anything previously about this new report, I asked the CAs to explain it to me – only to find out they also did not know anything about the report.  I went back and looked at March 2019 edition of New Directions and don’t see any mention of the PSA there.  The stealth rollout puts the CAs in a tough spot. The scoring categories look at Barberscore as generally  a contest administration thing, so we immediately turn to our CA teammates to explain what's going on. Let's give them some air cover.

**Comment by millsjdm** [comment]
We're going to await more feedback on SA and PSA over the next few weeks this spring prior to asking for additional changes. Meanwhile, we intend to provide hands-on training at category school this summer to be able to train on these reports as well.
