### ISSUE TITLE
Chg Finish Round to Complete Round

### ISSUE THREAD

**Issue by CLBuechler2324** [barberscore/barberscore-api#494]
After observations of last weekend’s contests and conversations with a number of CAs,
I am concerned with wording of “Finish Round”  There is a finality to that that is giving great pause, even with Verification and Publishing afterwards.  Recommending it be “Complete Round”

**Comment by CLBuechler2324** [comment]
While not critical, would like to update video to reflect new term. EDC for completion?

**Comment by dbinetti** [comment]
should get to that shortly

**Comment by dbinetti** [comment]
is this something you want done before tonight, or should I wait until this weekend is over?

**Comment by CLBuechler** [comment]
At this point it can wait.  I was hoping to do a new video but it can wait until Monday.

**Comment by CLBuechler2324** [comment]
It can wait until after contests this weekend.

Chris
Sent from my iPhone6s+



Chris

**Comment by dbinetti** [comment]
I will try to get this done tomorrow before this weekend.  Dealing with the MC this week just took all my BS time.

**Comment by CLBuechler** [comment]
Understand

Chris
