### ISSUE TITLE
Enhance Variance Sheet

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#498]
In addition to the "black bars" that are visible on the variance sheet (to highlight which category is involved with the variance score), would it be possible to render the actual variance score (or scores) to be bold-italicized as well?
While techincally all the scores (in that category) are "eligible" to be changed by the judges involved. many judges would still like to know which score (or scores) actually "triggered" the variance report in the first place.

**Comment by millsjdm** [comment]
Reconsidered... let's train on this at category school - a much better approach. Closed.

**Comment by CLBuechler2324** [comment]
FWIW I agree. If its not obvious, I fail to see need to point out miscreant.
