### ISSUE TITLE
Groups should not advance if they are not in top X scores

### ISSUE THREAD

**Issue by CLBuechler2324** [barberscore/barberscore-api#544]
@dbinetti Dealer's Choice award is 3-round contest, but entrants normally do not advance to finals. Appears the top DC entrant will advance automatically regardless of score,

**Comment by dbinetti** [comment]
I can fix this fairly easily, but I think I'm going to fix #506 first; this will provide a fairly obvious use case for testing, even if it's a unique condition.  we have time to get this right.

**Comment by CLBuechler2324** [comment]
Fine.  We will need to RMD and ILL in the fall at a minimum.

**Comment by dbinetti** [comment]
Verified this works as anticipated.  If you experience this again lmk -- but it also could have been related to mocking the contest since I didn't really change any code.

**Comment by CLBuechler2324** [comment]
Okay, should I run staging without mocking?

**Comment by dbinetti** [comment]
You should do most of your testing using mocking, just because it's so much
faster.  Use this to uncover any obvious or corner cases.

That said, at some point before the contest it might be worth running a
full end-to-end simulation just to replicate the real-word as closely as
possible.
