### ISSUE TITLE
Ability to generate Awards report by district

### ISSUE THREAD

**Issue by CLBuechler2324** [barberscore/barberscore-api#546]
Need report for each DRCJ to indicates all awards in district:
- Award name
- Kind
- Gender
- Season
- Level
- Single?
- Threshold

**Comment by dbinetti** [comment]
[awards.xlsx](https://github.com/barberscore/barberscore-api/files/3279478/awards.xlsx)

**Comment by CLBuechler2324** [comment]
Unfortunately, after looking at the file format, more data is needed in order to make it useful. 
I implicitly wanted it by 'district' so Group is necessary. Also add Spots, Minimum and Advance.
Thanks.

**Comment by CLBuechler2324** [comment]
Pls reopen to provide more data per note.

**Comment by dbinetti** [comment]
@CLBuechler2324 FYI there is a button on the site that says "reopen and comment".  sorry I didn't see this sooner.

**Comment by CLBuechler2324** [comment]
Thanks!
