### ISSUE TITLE
Invalid Member Data from MC

### ISSUE THREAD

**Issue by millsjdm** [barberscore/barberscore-api#548]
Unfortunately - I sent out several emails to all quartets competing in SLC Intl contest with members that need to update their BHS subscriptions based on Barberscore info. As it turned out (after checking each individual member in MC) - over half of those were not true.
To see all those use cases (well over 12 of them) - you can look at all of those entries that have "All valid in MC" in the comments.

This is a lower priority (for now) - clearly we're still dealing with weird state info from MC. However, prior to the fall 2019 season, it would be nice to get these anomalies solved with MC.

**Comment by dbinetti** [comment]
I don't know what you're asking.  Checking Forecast, which has "All valid
in MC", shows mikefitch@triad.rr.com which matches the Member Center
everywhere I can see -- front end., back end, etc.  So what exactly is the
problem?

If you're saying "The member center has inaccurate information" then yes,
that's true all over the place.  Bad emails, bad phone numbers, meta data
in name fields, the entire name in the first name field..  I've given up
caring.

**Comment by millsjdm** [comment]
I'm looking at Mike via the front-end UI... still shows his expiration as
6/30/2019 - (and yes, I refreshed several times)  :-)
[image: image.png]

*J. David Mills*
SCJC Chairman 2016-2019
*Mobile Phone - 813.786.4381*

*Singing is Life is Singing is…*

**Comment by dbinetti** [comment]
You said “I sent  out emails half of which we’re not true.”  So are the emails wrong or is something else wrong?

**Comment by millsjdm** [comment]
I just meant that I trusted the data (via Barberscore front-end UI) without checking MC. So I ended up sending emails to more groups than I should have. No big deal, because I told the groups that if they're okay - just ignore my "warning" email. For those that truly are delinquent in dues - they needed to get the email.

**Comment by dbinetti** [comment]
Closing in favor of #549
